distro UPDATE major package script update

diff --git a/distro/pkg/deb/netopeer2.prerm b/distro/pkg/deb/netopeer2.prerm
--- a/distro/pkg/deb/netopeer2.prerm
+++ b/distro/pkg/deb/netopeer2.prerm
@@ -1,19 +1,19 @@
 #!/bin/sh
-# postrm script for netopeer2
+# prerm script for netopeer2
 #
 # see: dh_installdeb(1)
 
 set -e
 
 # summary of how this script can be called:
-#        * <postrm> `remove'
-#        * <postrm> `purge'
-#        * <old-postrm> `upgrade' <new-version>
-#        * <new-postrm> `failed-upgrade' <old-version>
-#        * <new-postrm> `abort-install'
-#        * <new-postrm> `abort-install' <old-version>
-#        * <new-postrm> `abort-upgrade' <old-version>
-#        * <disappearer's-postrm> `disappear' <overwriter>
+#        * <prerm> `remove'
+#        * <prerm> `purge'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <new-prerm> `abort-install'
+#        * <new-prerm> `abort-install' <old-version>
+#        * <new-prerm> `abort-upgrade' <old-version>
+#        * <disappearer's-prerm> `disappear' <overwriter>
 #          <overwriter-version>
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
@@ -34,13 +34,13 @@ case "$1" in
 	    NP2_MODULE_PERMS=660 \
 	    NP2_MODULE_OWNER=root \
 	    NP2_MODULE_GROUP=netconf \
-	    bash -r /usr/share/netopeer2/remove.sh
+	    bash /usr/share/netopeer2/remove.sh
     ;;
     upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
     ;;
 
     *)
-        echo "postrm called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
